name: Deploy Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: agranelos-fybpb6duaadaaxfm
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  JAVA_VERSION: '11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSL_MODE: 'disable'
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Java SDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'maven'

    - name: 'Restore Project Dependencies Using Maven'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        mvn clean package
        popd

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      run: |
        cd target/azure-functions/agranelos-inventario-functions
        zip -r ../deploy.zip .
        az functionapp deployment source config-zip \
          --resource-group agranelos \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --src ../deploy.zip

    - name: 'Notify Deployment Success'
      if: success()
      run: |
        echo "✅ Deployment completed successfully!"
        echo "Function App URL: https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"

    - name: 'Notify Deployment Failure'
      if: failure()
      run: |
        echo "❌ Deployment failed. Check the logs for details."
