name: Build, Test, and Deploy Java project to Azure Function App - agranelos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: agranelos
  PACKAGE_DIRECTORY: "."
  JAVA_VERSION: "11"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSL_MODE: ${{ secrets.DB_SSL_MODE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: microsoft

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Restore dependencies
        run: |
          pushd $PACKAGE_DIRECTORY
          mvn clean compile
          popd

      - name: Run tests
        run: |
          pushd $PACKAGE_DIRECTORY
          mvn test
          popd

      - name: Package application
        run: |
          pushd $PACKAGE_DIRECTORY
          mvn clean package
          popd

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_DIRECTORY }}/target/azure-functions/agranelos-inventario-functions
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_233EB9B85DE548C18A928AC4CADA2CCE }}
          slot-name: Production
          sku: flexconsumption
